## Вычисления с помощью Numpy. 
##### Задание 1

In [2]:
import numpy as np

In [3]:
#Создайте массив Numpy под названием a размером 5x2, то есть состоящий из 5 строк и 2 столбцов. 
#Первый столбец должен содержать числа 1, 2, 3, 3, 1, а второй - числа 6, 8, 11, 10, 7.
a = np.array ([[1, 6],
               [2, 8],
               [3, 11],
               [3, 10],
               [1, 7]]) 
a

array([[ 1,  6],
       [ 2,  8],
       [ 3, 11],
       [ 3, 10],
       [ 1,  7]])

In [4]:
mean_a = a.mean(axis = 0)
mean_a

array([2. , 8.4])

##### Задание 2

In [5]:
# Вычислите массив a_centered, отняв от значений массива “а” средние значения соответствующих признаков, 
# содержащиеся в массиве mean_a.
a_centered = a - mean_a
a_centered

array([[-1. , -2.4],
       [ 0. , -0.4],
       [ 1. ,  2.6],
       [ 1. ,  1.6],
       [-1. , -1.4]])

In [6]:
# 2 способ
a_centered = np.subtract(a, mean_a)
a_centered

array([[-1. , -2.4],
       [ 0. , -0.4],
       [ 1. ,  2.6],
       [ 1. ,  1.6],
       [-1. , -1.4]])

##### Задание 3

In [7]:
# Найдите скалярное произведение столбцов массива a_centered
a_centered_sp = np.dot(a_centered.T[0], a_centered.T[1])
a_centered_sp

8.0

In [8]:
# Поделите a_centered_sp на N-1, где N - число наблюдений.
a_centered_sp / (a_centered.shape[0] - 1)

2.0

##### Задание 4**

In [9]:
# Вычислить ковариацию с помощью функции np.cov. 
# В качестве аргумента m функция np.cov должна принимать транспонированный массив “a”. 
# В получившейся ковариационной матрице (массив Numpy размером 2x2) искомое значение ковариации будет равно 
# элементу в строке с индексом 0 и столбце с индексом 1.

cov_a = np.cov(a.T) 
cov_a[0][1]

2.0

 ##### Задание 5**

In [10]:
import random

In [11]:
#Создайте одномерный массив z случайных равномерно распределенных целых чисел от -50 до 50 включительно размерности 8. 
#Найдите индексы положительных объектов.
np.random.seed(42)
z = np.random.randint(-50, 51, 9)
z

array([  1,  42, -36,  21,  10, -30,  32,  36,  24])

In [12]:
positive_ind = np.where(z>0)
positive_ind

(array([0, 1, 3, 4, 6, 7, 8]),)

 ##### Задание 6** - стандартизация данных

In [13]:
#Создайте двумерный массив X случайных равномерно распределенных целых чисел от 0 до 255 включительно 
#размерности 10 на 5.

X = np.random.randint(0, 255, (10, 5))
X

array([[202,  87, 116,  99, 103],
       [151, 130, 149,  52,   1],
       [ 87, 235, 157,  37, 129],
       [191, 187,  20, 160, 203],
       [ 57,  21, 252, 235,  88],
       [ 48, 218,  58, 254, 169],
       [219, 187, 207,  14, 189],
       [189, 174, 189,  50, 107],
       [ 54, 243,  63, 248, 130],
       [228,  50, 134,  20,  72]])

In [14]:
#Найдите среднее значение и стандартное отклонение по каждому признаку.
X_mean = X.mean(axis = 0)
X_mean

array([142.6, 153.2, 134.5, 116.9, 119.1])

In [15]:
X_std = X.std(axis = 0)
X_std

array([69.60057471, 73.97269767, 68.67787125, 93.35893101, 56.71939703])

In [16]:
#Вычислите массив X_standard, отняв от каждого признака среднее и поделив на стандартное отклонение.
X_standard = (X - X_mean) / X_std
X_standard

array([[ 0.85344123, -0.89492478, -0.26937352, -0.19173313, -0.28385351],
       [ 0.12068866, -0.31362923,  0.2111306 , -0.69516649, -2.0821801 ],
       [-0.79884398,  1.1058134 ,  0.32761644, -0.85583671,  0.17454346],
       [ 0.69539656,  0.45692534, -1.66720368,  0.4616591 ,  1.47921178],
       [-1.2298749 , -1.78714585,  1.71088588,  1.2650102 , -0.5483133 ],
       [-1.35918418,  0.87599888, -1.11389591,  1.46852581,  0.87976958],
       [ 1.09769209,  0.45692534,  1.05565299, -1.10219771,  1.23238264],
       [ 0.66666116,  0.28118482,  0.79355983, -0.71658918, -0.2133309 ],
       [-1.27297799,  1.21396141, -1.04109226,  1.40425772,  0.19217412],
       [ 1.22700136, -1.39510932, -0.00728037, -1.03792962, -0.83040375]])

In [17]:
#Убедитесь, что теперь среднее в каждом признаке стало равное нулю, а стандартное отклонение равно единице.
X_standard.mean(axis = 0)

# среднее не равно 0, уточнить 

array([ 8.88178420e-17,  1.33226763e-16,  1.45716772e-17, -1.11022302e-16,
        1.11022302e-16])

In [18]:
X_standard.std(axis = 0)

array([1., 1., 1., 1., 1.])

 ##### Задание 7**

In [19]:
#Создайте два одномерных массива размерности 512 с любыми значениями. Каждый массив - наблюдение с 512 признаками. 
a = np.random.randint(1, 1000, 512)
b = np.random.randint(1000, 2000, 512)

In [20]:
#Найдите разницу между двумя массивами. 
#Далее возведите разницу в квадрат, просуммируйте все элементы нового массива и возьмите корень квадратный.
c = np.subtract(a, b)
c = c ** 2
c = c.sum()

from math import sqrt
c = sqrt(c)
c

24203.83599762649

L2-норма (Евклидова метрика) — функция расстояния, благодаря которой можно считать насколько далеки точки друг от друга, насколько они похожи друг на друга. 

In [21]:
#Посчитайте L2 норму для этих двух массивов с помощью numpy.linalg.
from numpy.linalg import norm
l2_norm = norm(a-b, ord = 2)
l2_norm

24203.83599762649

 ##### Задание 8** - нормализация данных

In [22]:
X = np.random.randint(0, 255, (10, 5))
#Найдите минимальное значение и максимальное по каждому признаку.
X_min = X.min(axis = 0)
X_min

array([16,  5, 49, 29, 28])

In [23]:
X_max = X.max(axis = 0)
X_max

array([228, 251, 251, 215, 251])

In [24]:
#Вычислите массив X_norm, отняв от каждого признака минимальное и поделив на разницу максимального и минимального.
X_norm = (X - X_min) / (X_max - X_min)
X_norm

array([[1.        , 0.32113821, 0.45544554, 0.19354839, 0.20627803],
       [0.76415094, 0.39430894, 0.57425743, 0.87096774, 1.        ],
       [0.98584906, 0.1300813 , 0.        , 0.3655914 , 0.23766816],
       [0.06132075, 0.29674797, 0.2029703 , 0.80107527, 0.7264574 ],
       [0.98584906, 0.18699187, 0.98514851, 0.7311828 , 0.87892377],
       [0.93867925, 0.29674797, 1.        , 0.        , 0.97757848],
       [0.41981132, 0.18292683, 0.15346535, 0.55376344, 0.        ],
       [0.54245283, 0.53658537, 0.66336634, 0.61827957, 0.20179372],
       [0.        , 1.        , 0.16831683, 1.        , 0.1793722 ],
       [0.08018868, 0.        , 0.01485149, 0.88172043, 0.78923767]])

In [25]:
X_max_norm = X_norm.max()
X_max_norm

1.0

In [26]:
X_min_norm = X_norm.min()
X_min_norm

0.0

## Работа с данными в Pandas 
##### Задание 1

In [27]:
import pandas as pd

In [28]:
# Создать датафрейм authors со столбцами author_id и author_name
authors = pd.DataFrame ({'author_id': [1, 2,3],
                        'author_name': ['Тургенев', 'Чехов', 'Островский']},
                       columns = ['author_id', 'author_name'])
authors

author_id author_name
0          1    Тургенев
1          2       Чехов
2          3  Островский

In [29]:
# Создать датафрейм book cо столбцами author_id, book_title и price
book = pd.DataFrame({'author_id': [1, 1, 1, 2, 2, 3, 3], 
                    'book_title': ['Отцы и дети', 'Рудин', 'Дворянское гнездо', 'Толстый и тонкий', 
                                   'Дама с собачкой', 'Гроза', 'Таланты и поклонники'], 
                    'price': [450, 300, 350, 500, 450, 370, 290]},
                    columns = ['author_id', 'book_title', 'price'])
book

author_id            book_title  price
0          1           Отцы и дети    450
1          1                 Рудин    300
2          1     Дворянское гнездо    350
3          2      Толстый и тонкий    500
4          2       Дама с собачкой    450
5          3                 Гроза    370
6          3  Таланты и поклонники    290

##### Задание 2

In [30]:
# Получите датафрейм authors_price, соединив датафреймы authors и books по полю author_id.
authors_price = pd.merge(authors, book, on = 'author_id', how = 'inner')
authors_price

author_id author_name            book_title  price
0          1    Тургенев           Отцы и дети    450
1          1    Тургенев                 Рудин    300
2          1    Тургенев     Дворянское гнездо    350
3          2       Чехов      Толстый и тонкий    500
4          2       Чехов       Дама с собачкой    450
5          3  Островский                 Гроза    370
6          3  Островский  Таланты и поклонники    290

##### Задание 3

In [31]:
#Создайте датафрейм top5, в котором содержатся строки из authors_price с пятью самыми дорогими книгами.
top5 = authors_price.nlargest(5, 'price')
top5

author_id author_name         book_title  price
3          2       Чехов   Толстый и тонкий    500
0          1    Тургенев        Отцы и дети    450
4          2       Чехов    Дама с собачкой    450
5          3  Островский              Гроза    370
2          1    Тургенев  Дворянское гнездо    350

##### Задание 4

In [32]:
#Создайте датафрейм authors_stat на основе информации из authors_price. В датафрейме authors_stat должны быть четыре столбца:
# author_name, min_price, max_price и mean_price,
# в которых должны содержаться соответственно имя автора,минимальная, максимальная и средняя цена на книги этого автора.

authors_stat = authors_price.groupby('author_name').agg({'price' : ['min', 'max', 'mean']})
authors_stat = authors_stat.rename(columns = {'min' : 'min_price', 'max' : 'max_price', 'mean' : 'mean_price'})
authors_stat

price                      
            min_price max_price  mean_price
author_name                                
Островский        290       370  330.000000
Тургенев          300       450  366.666667
Чехов             450       500  475.000000

##### Задание 5**

In [33]:
#Создайте новый столбец в датафрейме authors_price под названием cover
authors_price['cover'] = ['твердая', 'мягкая', 'мягкая', 'твердая', 'твердая', 'мягкая', 'мягкая']
authors_price

author_id author_name            book_title  price    cover
0          1    Тургенев           Отцы и дети    450  твердая
1          1    Тургенев                 Рудин    300   мягкая
2          1    Тургенев     Дворянское гнездо    350   мягкая
3          2       Чехов      Толстый и тонкий    500  твердая
4          2       Чехов       Дама с собачкой    450  твердая
5          3  Островский                 Гроза    370   мягкая
6          3  Островский  Таланты и поклонники    290   мягкая

Просмотрите документацию по функции pd. с помощью вопросительного знака.
Для каждого автора посчитайте суммарную стоимость книг в твердой и мягкой обложке. 
Используйте для этого функцию pd.pivot_table. При этом столбцы должны называться "твердая" и "мягкая", 
а индексами должны быть фамилии авторов. Пропущенные значения стоимостей заполните нулями, 
при необходимости загрузите библиотеку Numpy.
Назовите полученный датасет book_info и сохраните его в формат pickle под названием "book_info.pkl". Затем загрузите из этого файла датафрейм и назовите его book_info2. Удостоверьтесь, что датафреймы book_info и book_info2 идентичны.

In [34]:
?pd.pivot_table

In [35]:
book_info = pd.pivot_table(authors_price, index = 'author_name', values = 'price', columns = 'cover', aggfunc = np.sum)
book_info.fillna(0)

cover        мягкая  твердая
author_name                 
Островский    660.0      0.0
Тургенев      650.0    450.0
Чехов           0.0    950.0

In [36]:
book_info.to_pickle('book_info.pkl')

In [37]:
book_info2 = pd.read_pickle('book_info.pkl')

In [38]:
book_info == book_info2

cover        мягкая  твердая
author_name                 
Островский     True    False
Тургенев       True     True
Чехов         False     True

##### Задание 6**

In [39]:
#Ознакомьтесь с описанием данных и скачайте датасет netflix_titles.csv с сайта Kaggle.com 
df = pd.read_csv('netflix_titles.csv')

In [40]:
df.shape

(7787, 12)

В датасете Netflix 7787 строк (наблюдений) и 12 столбцов (признаков)

In [41]:
df.columns

Index(['show_id', 'type', 'title', 'director', 'cast', 'country', 'date_added',
       'release_year', 'rating', 'duration', 'listed_in', 'description'],
      dtype='object')

In [42]:
#смотрим количество фильмов и ТВ шоу
df['type'].value_counts()

Movie      5377
TV Show    2410
Name: type, dtype: int64

In [43]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7787 entries, 0 to 7786
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype 
---  ------        --------------  ----- 
 0   show_id       7787 non-null   object
 1   type          7787 non-null   object
 2   title         7787 non-null   object
 3   director      5398 non-null   object
 4   cast          7069 non-null   object
 5   country       7280 non-null   object
 6   date_added    7777 non-null   object
 7   release_year  7787 non-null   int64 
 8   rating        7780 non-null   object
 9   duration      7787 non-null   object
 10  listed_in     7787 non-null   object
 11  description   7787 non-null   object
dtypes: int64(1), object(11)
memory usage: 730.2+ KB


Пропущенные значения в столблцах director, cast, country, rating (мало, всего 7, можно будет заполнить средним или медианой)

In [44]:
df['director'].isnull().sum()

2389

In [45]:
df['cast'].isnull().sum()

718

In [46]:
df['country'].isnull().sum()

507

In [47]:
df['release_year'].dtype

dtype('int64')

In [48]:
df.loc[df['release_year'] < 2003, 'release_year'].count()

564

564 фильма вышли раньше 2003 года

In [49]:
df['country'].value_counts().nlargest(1)

United States    2555
Name: country, dtype: int64

Наибольшее количество фильмов на Netflix выпущено в США

##### Задание 7**

В этом датасете есть признак date_added (дата добавления сериала/фильма на платформу), на основе этого признака создайте три новых: year_added - год добавления, month_added - месяц добавления и day_added - день добавления.

In [50]:
#выведем значения head для того, чтобы увидеть внешний вид даты
df['date_added'].head(1)

0    August 14, 2020
Name: date_added, dtype: object

In [51]:
import datetime as dt

In [52]:
df['date_new'] = pd.to_datetime(df['date_added'], infer_datetime_format=True)
df['date_new'].head()

0   2020-08-14
1   2016-12-23
2   2018-12-20
3   2017-11-16
4   2020-01-01
Name: date_new, dtype: datetime64[ns]

In [53]:
df['year_added'] = df['date_new'].dt.year
df['month_added'] = df['date_new'].dt.month
df['day_added'] = df['date_new'].dt.day

In [54]:
df['year_added'].head(1)

0    2020.0
Name: year_added, dtype: float64

In [55]:
df['month_added'].head(10)

0     8.0
1    12.0
2    12.0
3    11.0
4     1.0
5     7.0
6     6.0
7    11.0
8     4.0
9    12.0
Name: month_added, dtype: float64

In [56]:
df['day_added'].head(1)

0    14.0
Name: day_added, dtype: float64

In [57]:
df = df.drop('date_new', axis = 1)

In [58]:
df.columns

Index(['show_id', 'type', 'title', 'director', 'cast', 'country', 'date_added',
       'release_year', 'rating', 'duration', 'listed_in', 'description',
       'year_added', 'month_added', 'day_added'],
      dtype='object')

##### Задание 8**

Выберите только наблюдения, где страна 'United States', 'India' или 'United Kingdom'
Для каждой страны посчитайте общее количество фильмов и сериалов по месяцам выпуска. Столбцы нового 
сводного датафрейма должны называться, как месяца в признаке month_added, а индексов будет два: страна и тип.

In [59]:
df1 = df.copy()

In [60]:
df1 = df1.loc[df1['country'].isin(['United States', 'India', 'United Kingdom']), :]

In [61]:
df1['country'].values

array(['United States', 'United States', 'United States', ..., 'India',
       'United States', 'India'], dtype=object)

In [62]:
df1.columns

Index(['show_id', 'type', 'title', 'director', 'cast', 'country', 'date_added',
       'release_year', 'rating', 'duration', 'listed_in', 'description',
       'year_added', 'month_added', 'day_added'],
      dtype='object')

In [63]:
df2 = df1.groupby(['country', 'type']).agg({'month_added':'count'})

In [64]:
df2

month_added
country        type                
India          Movie            852
               TV Show           71
United Kingdom Movie            193
               TV Show          203
United States  Movie           1850
               TV Show          699